### PR TITLE
Update eclipse-corinthian.jsonnet

### PR DESCRIPTION
**Pull request by andrewjskatz**
Creating a new repo

### CODE REVIEW

**Comment by netomi** [comment]
so what should be the repo's name?
and do you want to make it private for sure?

**Comment by andrewjskatz** [comment]
Thanks Thomas - that was a very rapid response!  


Pls can we call the repo “Precedent_Docs”, and can we make it public?

All the best



Andrew






Andrew Katz
***@***.***



On 4 Sep 2024, at 15:20, Thomas Neidhart ***@***.***> wrote:


so what should be the repo's name?
and do you want to make it private for sure?

**Review by netomi — APPROVED** [review]

**Comment by netomi** [comment]
so you can see at https://github.com/eclipse-corinthian/.eclipsefdn/pull/3#issuecomment-2329227654 what changes will be applied. This will create a new repository with default settings. If you want any of these settings changes, add the according key/value pair to the repo definition, otherwise I can go ahead and merge the change.

**Review by andrewjskatz — COMMENTED** [review]
Looks good to me!

**Comment by netomi** [comment]
the repo has been created, it might take up to 3 hours for the permissions to be updated, but you can already fork the repo and create PRs.

**Pull request merged**
